language: python

# Test matrix
python:
    - 3.7
    - 3.8
    - 3.9
    - 3.10

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

# Package installation
install:
  - pip install Pillow Wand
  - python setup.py install

# Run the tests
script:
  python runtests.py
