language: python

# Test matrix
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.4

# Package installation
install:
  - pip install unittest2
  - python setup.py install

# Run the tests
script:
  python runtests.py
