language: python

# Test matrix
python:
    - 2.7
    - 3.3
    - 3.4

# Package installation
install:
  - pip install Pillow Wand
  - python setup.py install

# Run the tests
script:
  python runtests.py
